const moroccanCities = [
    "Casablanca",
    "El Kelaa des Srarhna",
    "Fès",
    "Tangier",
    "Marrakech",
    "Sale",
    "Mediouna",
    "Rabat",
    "Meknès",
    "Oujda-Angad",
    "Kenitra",
    "Agadir",
    "Tétouan",
    "Taourirt",
    "Temara",
    "Safi",
    "Khénifra",
    "Laâyoune",
    "Mohammedia",
    "Kouribga",
    "El Jadida",
    "Béni Mellal",
    "Ait Melloul",
    "Nador",
    "Taza",
    "Settat",
    "Barrechid",
    "Al Khmissat",
    "Inezgane",
    "Ksar El Kebir",
    "Larache",
    "Guelmim",
    "Berkane",
    "Khemis Sahel",
    "Ad Dakhla",
    "Bouskoura",
    "Al Fqih Ben Çalah",
    "Oued Zem",
    "Sidi Slimane",
    "Errachidia",
    "Guercif",
    "Oulad Teïma",
    "Ben Guerir",
    "Sefrou",
    "Fnidq",
    "Sidi Qacem",
    "Moulay Abdallah",
    "Youssoufia",
    "Martil",
    "Aïn Harrouda",
    "Skhirate",
    "Ouezzane",
    "Sidi Yahya Zaer",
    "Al Hoceïma",
    "M'diq",
    "Sidi Bennour",
    "Midalt",
    "Azrou",
    "My Drarga",
    "Ain El Aouda",
    "Beni Yakhlef",
    "Ad Darwa",
    "Al Aaroui",
    "Qasbat Tadla",
    "Boujad",
    "Jerada",
    "Mrirt",
    "El Aïoun",
    "Azemmour",
    "Temsia",
    "Zagora",
    "Ait Ourir",
    "Aziylal",
    "Sidi Yahia El Gharb",
    "Biougra",
    "Zaïo",
    "Aguelmous",
    "El Hajeb",
    "Zeghanghane",
    "Imzouren",
    "Tit Mellil",
    "Mechraa Bel Ksiri",
    "Al ’Attawia",
    "Demnat",
    "Arfoud",
    "Tameslouht",
    "Bou Arfa",
    "Sidi Smai'il",
    "Souk et Tnine Jorf el Mellah",
    "Mehdya",
    "Aïn Taoujdat",
    "Chichaoua",
    "Tahla",
    "Oulad Yaïch",
    "Moulay Bousselham",
    "Iheddadene",
    "Missour",
    "Zawyat ech Cheïkh",
    "Bouknadel",
    "Oulad Tayeb",
    "Oulad Barhil",
    "Bir Jdid",
    "Tifariti",
    ];
export default moroccanCities;